# Generated by Django 5.2.4 on 2025-08-01 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('cnic', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('absents', models.IntegerField()),
                ('short_shift', models.IntegerField()),
                ('late', models.IntegerField()),
                ('half_day', models.IntegerField()),
                ('deduction_days', models.FloatField()),
                ('final_salary', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_slips', to='salaryapp.employee')),
            ],
        ),
    ]
